// Database schema types for Supabase tables
// Ensures type safety for admin panel queries

export interface DatabaseProduct {
  id: string; // UUID generated by Supabase
  name: string;
  slug?: string; // URL-friendly identifier for frontend mapping
  category: string;
  description?: string;
  images: string[]; // Array of image URLs from Supabase Storage
  created_at?: string;
  updated_at?: string;
}

export interface DatabaseVariant {
  id: string; // UUID generated by Supabase
  product_id: string; // FK to products.id (UUID)
  product_name?: string; // Denormalized product name for easier CSV exports
  sku?: string;
  price: number;
  stock_qty: number;
  option_values: Record<string, string>; // JSON object, e.g. {"size": "Large"}
  created_at?: string;
  updated_at?: string;
}

export interface WebsiteProduct {
  id: string; // String slug matching frontend product IDs
  name: string;
  slug?: string;
  category?: string;
}

// Helper type for dropdown options
export interface ProductOption {
  id: string;
  name: string;
}
